### Customer Churn Analysis & Business Intelligence Dashboard

In [52]:
import pandas as pd

df = pd.read_csv("../1-Data/Raw/telco.csv")

df.head()

,Customer ID,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Country,State,...,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Satisfaction Score,Customer Status,Churn Label,Churn Score,CLTV,Churn Category,Churn Reason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,...,20,0.00,59.65,3,Churned,Yes,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,...,0,390.80,1024.10,3,Churned,Yes,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,...,0,203.94,1910.88,2,Churned,Yes,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,...,0,494.00,2995.07,2,Churned,Yes,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,...,0,234.21,3102.36,2,Churned,Yes,67,2793,Price,Extra data charges

### Chek data is clean or not

In [53]:
df.shape
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 50 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   object
 1   Gender                             7043 non-null   object
 2   Age                                7043 non-null   int64
 3   Under 30                           7043 non-null   object
 4   Senior Citizen                     7043 non-null   object
 5   Married                            7043 non-null   object
 6   Dependents                         7043 non-null   object
 7   Number of Dependents               7043 non-null   int64
 8   Country                            7043 non-null   object
 9   State                              7043 non-null   object
 10  City                               7043 non-null   object
 11  Zip Code                           7043 non-null   int64
 12  Latitude                           7043 non-null   float64
 13  Longitude                          7043 non-null   float64
 14  Population                         7043 non-null   int64
 15  Quarter                            7043 non-null   object
 16  Referred a Friend                  7043 non-null   object
 17  Number of Referrals                7043 non-null   int64
 18  Tenure in Months                   7043 non-null   int64
 19  Offer                              3166 non-null   object
 20  Phone Service                      7043 non-null   object
 21  Avg Monthly Long Distance Charges  7043 non-null   float64
 22  Multiple Lines                     7043 non-null   object
 23  Internet Service                   7043 non-null   object
 24  Internet Type                      5517 non-null   object
 25  Avg Monthly GB Download            7043 non-null   int64
 26  Online Security                    7043 non-null   object
 27  Online Backup                      7043 non-null   object
 28  Device Protection Plan             7043 non-null   object
 29  Premium Tech Support               7043 non-null   object
 30  Streaming TV                       7043 non-null   object
 31  Streaming Movies                   7043 non-null   object
 32  Streaming Music                    7043 non-null   object
 33  Unlimited Data                     7043 non-null   object
 34  Contract                           7043 non-null   object
 35  Paperless Billing                  7043 non-null   object
 36  Payment Method                     7043 non-null   object
 37  Monthly Charge                     7043 non-null   float64
 38  Total Charges                      7043 non-null   float64
 39  Total Refunds                      7043 non-null   float64
 40  Total Extra Data Charges           7043 non-null   int64
 41  Total Long Distance Charges        7043 non-null   float64
 42  Total Revenue                      7043 non-null   float64
 43  Satisfaction Score                 7043 non-null   int64
 44  Customer Status                    7043 non-null   object
 45  Churn Label                        7043 non-null   object
 46  Churn Score                        7043 non-null   int64
 47  CLTV                               7043 non-null   int64
 48  Churn Category                     1869 non-null   object
 49  Churn Reason                       1869 non-null   object
dtypes: float64(8), int64(11), object(31)
memory usage: 2.7+ MB

np.int64(0)

### Proper Cleaning

In [54]:
# 1️⃣ Standardize column names (very important)
df.columns = df.columns.str.strip().str.replace(" ", "_")

# 2️⃣ Handle Offer column
df['Offer'] = df['Offer'].fillna("No_Offer")

# 3️⃣ Handle Internet_Type
df['Internet_Type'] = df['Internet_Type'].fillna("No_Internet")

# 4️⃣ Handle churn related columns
df['Churn_Category'] = df['Churn_Category'].fillna("No_Churn")
df['Churn_Reason'] = df['Churn_Reason'].fillna("Not_Applicable")

# 5️⃣ Convert categorical Yes/No columns to consistent format
yes_no_cols = df.select_dtypes(include='object').columns

for col in yes_no_cols:
    df[col] = df[col].str.strip()

# 6️⃣ Check again
df.isnull().sum()

Customer_ID                          0
Gender                               0
Age                                  0
Under_30                             0
Senior_Citizen                       0
Married                              0
Dependents                           0
Number_of_Dependents                 0
Country                              0
State                                0
City                                 0
Zip_Code                             0
Latitude                             0
Longitude                            0
Population                           0
Quarter                              0
Referred_a_Friend                    0
Number_of_Referrals                  0
Tenure_in_Months                     0
Offer                                0
Phone_Service                        0
Avg_Monthly_Long_Distance_Charges    0
Multiple_Lines                       0
Internet_Service                     0
Internet_Type                        0
Avg_Monthly_GB_Download              0
Online_Security                      0
Online_Backup                        0
Device_Protection_Plan               0
Premium_Tech_Support                 0
Streaming_TV                         0
Streaming_Movies                     0
Streaming_Music                      0
Unlimited_Data                       0
Contract                             0
Paperless_Billing                    0
Payment_Method                       0
Monthly_Charge                       0
Total_Charges                        0
Total_Refunds                        0
Total_Extra_Data_Charges             0
Total_Long_Distance_Charges          0
Total_Revenue                        0
Satisfaction_Score                   0
Customer_Status                      0
Churn_Label                          0
Churn_Score                          0
CLTV                                 0
Churn_Category                       0
Churn_Reason                         0
dtype: int64

### Select target columns

In [55]:
target = 'Churn_Label'

In [56]:
df['Churn_Label'].value_counts()

Churn_Label
No     5174
Yes    1869
Name: count, dtype: int64

### Remove useless columns

In [57]:
drop_cols = [
    'Customer_ID',
    'Zip_Code',
    'Latitude',
    'Longitude'
]

df.drop(columns=drop_cols, inplace=True)

In [58]:
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 46 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gender                             7043 non-null   object
 1   Age                                7043 non-null   int64
 2   Under_30                           7043 non-null   object
 3   Senior_Citizen                     7043 non-null   object
 4   Married                            7043 non-null   object
 5   Dependents                         7043 non-null   object
 6   Number_of_Dependents               7043 non-null   int64
 7   Country                            7043 non-null   object
 8   State                              7043 non-null   object
 9   City                               7043 non-null   object
 10  Population                         7043 non-null   int64
 11  Quarter                            7043 non-null   object
 12  Referred_a_Friend                  7043 non-null   object
 13  Number_of_Referrals                7043 non-null   int64
 14  Tenure_in_Months                   7043 non-null   int64
 15  Offer                              7043 non-null   object
 16  Phone_Service                      7043 non-null   object
 17  Avg_Monthly_Long_Distance_Charges  7043 non-null   float64
 18  Multiple_Lines                     7043 non-null   object
 19  Internet_Service                   7043 non-null   object
 20  Internet_Type                      7043 non-null   object
 21  Avg_Monthly_GB_Download            7043 non-null   int64
 22  Online_Security                    7043 non-null   object
 23  Online_Backup                      7043 non-null   object
 24  Device_Protection_Plan             7043 non-null   object
 25  Premium_Tech_Support               7043 non-null   object
 26  Streaming_TV                       7043 non-null   object
 27  Streaming_Movies                   7043 non-null   object
 28  Streaming_Music                    7043 non-null   object
 29  Unlimited_Data                     7043 non-null   object
 30  Contract                           7043 non-null   object
 31  Paperless_Billing                  7043 non-null   object
 32  Payment_Method                     7043 non-null   object
 33  Monthly_Charge                     7043 non-null   float64
 34  Total_Charges                      7043 non-null   float64
 35  Total_Refunds                      7043 non-null   float64
 36  Total_Extra_Data_Charges           7043 non-null   int64
 37  Total_Long_Distance_Charges        7043 non-null   float64
 38  Total_Revenue                      7043 non-null   float64
 39  Satisfaction_Score                 7043 non-null   int64
 40  Customer_Status                    7043 non-null   object
 41  Churn_Label                        7043 non-null   object
 42  Churn_Score                        7043 non-null   int64
 43  CLTV                               7043 non-null   int64
 44  Churn_Category                     7043 non-null   object
 45  Churn_Reason                       7043 non-null   object
dtypes: float64(6), int64(10), object(30)
memory usage: 2.5+ MB

np.int64(0)

In [59]:
df['Churn_Label'] = df['Churn_Label'].map({'Yes': 1, 'No': 0})

In [60]:
df['Churn_Label'].value_counts()
df['Churn_Label'].value_counts(normalize=True)*100

Churn_Label
0    73.463013
1    26.536987
Name: proportion, dtype: float64

In [61]:
churn_rate = df['Churn_Label'].mean() * 100
print(f"Churn Rate: {churn_rate:.2f}%")

Churn Rate: 26.54%

### Business Objective

#### The telecom company is experiencing customer churn.
#### The objective of this analysis is to identify key churn drivers, measure financial impact, and recommend data-driven customer retention strategies.

Key Performance Indicators (KPIs)

We will measure:

Total Customers

Total Churned Customers

Churn Rate (%)

Total Revenue

Revenue Lost Due to Churn

Average Tenure (Churn vs Non-Churn)

Customer Lifetime Value (CLTV)

In [21]:
total_customers = len(df)
total_churned = df['Churn_Label'].sum()
churn_rate = df['Churn_Label'].mean()*100
total_revenue = df['Total_Revenue'].sum()
revenue_lost = df[df['Churn_Label']==1]['Total_Revenue'].sum()

print(f"Total Customers: {total_customers}")
print(f"Total Churned Customers: {total_churned}")
print(f"Churn Rate: {churn_rate:.2f}%")
print(f"Total Revenue: ${total_revenue:,.2f}")
print(f"Revenue Lost Due to Churn: ${revenue_lost:,.2f}")

Total Customers: 7043
Total Churned Customers: 1869
Churn Rate: 26.54%
Total Revenue: $21,371,131.69
Revenue Lost Due to Churn: $3,684,459.82

### Insights

In [22]:
revenue_lost / total_revenue * 100

np.float64(17.240358973240692)

The company is losing approximately 26.5% of customers, resulting in $3.68 million revenue loss, which represents nearly 17% of total revenue.

## Insight Extraction

In [28]:
# 1. Average tenure of churned customers
df[df['Churn_Label']==1]['Tenure_in_Months'].mean()

np.float64(17.979133226324237)

In [27]:
# 2. Churn by Contract Type
pd.crosstab(df['Contract'], df['Churn_Label'], normalize='index')*100

Churn_Label             0          1
Contract
Month-to-Month  54.155125  45.844875
One Year        89.290323  10.709677
Two Year        97.450876   2.549124

In [29]:
# 3. Churn by Payment Method
pd.crosstab(df['Payment_Method'], df['Churn_Label'], normalize='index')*100

Churn_Label              0          1
Payment_Method
Bank Withdrawal  66.001535  33.998465
Credit Card      85.522008  14.477992
Mailed Check     63.116883  36.883117

In [30]:
# 4. Top 5 Churn Reasons
df[df['Churn_Label']==1]['Churn_Reason'].value_counts().head()

Churn_Reason
Competitor had better devices    313
Competitor made better offer     311
Attitude of support person       220
Don't know                       130
Competitor offered more data     117
Name: count, dtype: int64

In [31]:
# High-risk customers profile
high_risk = df[
    (df['Contract'] == 'Month-to-Month') &
    (df['Tenure_in_Months'] < 18) &
    (df['Payment_Method'] == 'Mailed Check')
]

high_risk.shape

(200, 47)